<?php
$page="Feedback";
require_once($_SERVER["DOCUMENT_ROOT"]."/cadeui/system/includes/header.php");
?>
<body>
<?php
require_once($_SERVER["DOCUMENT_ROOT"]."/cadeui/system/includes/page-header.php");
?>
<h1>Feedback</h1>
<?php
require_once($_SERVER["DOCUMENT_ROOT"]."/cadeui/system/includes/footer.php");
require_once($_SERVER["DOCUMENT_ROOT"]."/cadeui/system/includes/js-files.php");
?>
</body>
</html>